name: Build

on: [push]

jobs:
  build_solution:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.0-rc.1
    - name: Build .NET Solution
      run: dotnet build "src\prospectScraper\prospectScraper.sln" --configuration Release
